version: '3'

name: test-dev
services:
  mission-dev:
    image: ${APP_ENTRY_ENV_DOCKER_IMAGE}:1.0.0-dev-dev.934a83a.b157
    container_name: test-dev
    environment:
      - QUARKUS_DATASOURCE_USERNAME=${APP_ENTRY_ENV_QUARKUS_DATASOURCE_USERNAME}
      - QUARKUS_DATASOURCE_PASSWORD=${APP_ENTRY_ENV_QUARKUS_DATASOURCE_PASSWORD}
      - QUARKUS_DATASOURCE_JDBC_URL=${APP_ENTRY_ENV_QUARKUS_DATASOURCE_JDBC_URL}
      - QUARKUS_HIBERNATE_ORM_LOG_SQL=false
      - QUARKUS_HIBERNATE_ORM_LOG_BIND_PARAMETERS=false
      - QUARKUS_LOG_CONSOLE_JSON=false
      - QUARKUS_HTTP_PORT=10000
      - DAPR_GRPC_PORT=3501
      - QUARKUS_SCHEDULER_ENABLED=true
      - PARAM=1

    logging:
      options:
        max-size: 100m
        max-file: "2"
          # agent目录挂载      
    #volumes:
      #- "/opt/data-dev/skywalking-agent/mission:/work/skywalking-agent"
  test-dev-dapr:
    image: "daprio/daprd:1.11.2"
    container_name: test-dev-dapr
    command:
      [
        "./daprd",
        "-app-id",
        "mission-dev",
        "-app-port",
        "10000",
        "--app-protocol",
        "http",
        "--dapr-http-port",
        "3500",
        "-dapr-grpc-port",
        "3501",
        "-components-path",
        "/components",
        "--log-as-json",
        "true",
        # dapr trace config配置
        "--config",
        "/components/config.yaml"
      ]
    #volumes:
      #- "/opt/data-dev/dapr/mission:/components"
    depends_on:
      - test-dev
    network_mode: "service:test-dev"
    logging:
      options:
        max-size: 100m
        max-file: "2"
networks:
  default:
    name: zxf
    external: true
